spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socks?useSSL=false
    username: root
    password: wangshihao
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: "classpath*:mapper/*.xml"